language: python

python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"

install:
  - pip install coveralls

# command to run tests
script:
  - py.test -v

# call Coveralls
after_success:
  - coveralls
